import byname from '../dict/byname-tr-en.json' with { type: 'json' };
import chrome from '../dict/chrome-tr-en.json' with { type: 'json' };
import consumables from '../dict/consumables-tr-en.json' with { type: 'json' };
import extra from '../dict/extra-tr-en.json' with { type: 'json' };
import fellows from '../dict/fellows-tr-en.json' with { type: 'json' };
import history from '../dict/history-tr-en.json' with { type: 'json' };
import items from '../dict/items-tr-en.json' with { type: 'json' };
import purchase from '../dict/purchase-tr-en.json' with { type: 'json' };

/**
 * The shipped dictionaries, imported statically so the bundler embeds them in
 * the executable. They are the seed for config/dict, which is what actually
 * gets loaded at runtime -- see src/paths.mjs.
 *
 * Insertion order is the alphabetical order the loader relies on: when two files
 * translate the same Turkish string, the later one wins. items-* is generated
 * from the game's own string tables, so it deliberately comes last and overrides
 * the hand-written files.
 *
 * Where each comes from:
 *   items-*   generated from both clients' string tables by exact text match
 *   byname-*  generated by matching the mall's item name to a table row
 *   chrome-*  hand-written fixed UI (tabs, headers, buttons) plus regex patterns
 *   others    hand-written wording that appears only in the mall
 */
export const EMBEDDED = {
  'byname-tr-en.json': byname,
  'chrome-tr-en.json': chrome,
  'consumables-tr-en.json': consumables,
  'extra-tr-en.json': extra,
  'fellows-tr-en.json': fellows,
  'history-tr-en.json': history,
  'items-tr-en.json': items,
  'purchase-tr-en.json': purchase,
};
