import fs from 'node:fs';
import path from 'node:path';
import { sameValues } from './values.mjs';

import { EMBEDDED } from './embedded.mjs';
import { DICT_DIR } from './paths.mjs';

/**
 * Turkish -> English rewriting for the webmall's HTML.
 *
 * Separated from the proxy so it can be tested without opening a socket.
 * Guarantees, enforced by construction rather than by intent:
 *   - only text BETWEEN tags is rewritten; attribute values (package_id, href,
 *     onclick) are never seen by the translator
 *   - <script> and <style> bodies are parked before the text walk and restored after
 *   - a rewritten chunk is REVERTED when its numbers change, reusing the build's
 *     value guard, so prices, Silk amounts and level requirements cannot move
 */
const MARK_OPEN = '@@SR';
const MARK_CLOSE = 'SR@@';

/**
 * Every *-tr-en.json in `dir`, or null when there is nothing to read. A file
 * that fails to parse is reported and skipped: one bad edit must not take the
 * whole dictionary down.
 */
function readDir(dir) {
  if (!dir || !fs.existsSync(dir)) return null;
  const out = {};
  for (const f of fs.readdirSync(dir)) {
    if (!/-tr-en\.json$/.test(f)) continue;
    try {
      out[f] = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
    } catch (e) {
      console.error(`  ! ignoring ${path.join(dir, f)} -- invalid JSON: ${e.message}`);
    }
  }
  return Object.keys(out).length ? out : null;
}

/**
 * The dictionary in use: config/dict when it has been seeded, the embedded copy
 * otherwise.
 *
 * The bundled data covers the mall as it was captured:
 *   items-*   generated from the clients' string tables by exact text
 *   byname-*  generated by matching the mall's item name to a table row
 *   chrome-*  hand-written fixed UI, plus the regex patterns
 *   others    hand-written wording that exists only in the mall
 *
 * Editing those files is the supported way to change or replace the wording --
 * including translating the mall into another language entirely. No rebuild is
 * needed, and ensureConfig() never overwrites a value that is already there.
 */
export function loadDictionary({ dir = DICT_DIR } = {}) {
  // config/dict is the live dictionary; the embedded copy is only the fallback
  // for a first run that has not seeded it yet (see ensureConfig). Reading the
  // folder rather than merging over the embedded data means a string the user
  // deleted stays deleted.
  const source = readDir(dir) ?? EMBEDDED;

  const chrome = { ...(source['chrome-tr-en.json'] ?? {}) };
  const items = {};
  // Alphabetical, and it matters: the later file wins on a duplicate key.
  for (const name of Object.keys(source).sort()) {
    if (name.startsWith('chrome')) continue;
    Object.assign(items, source[name]);
  }

  const patterns = Object.entries(chrome._patterns || {})
    .filter(([k]) => !k.startsWith('_'))
    .map(([re, rep]) => [new RegExp(re, 'g'), rep]);

  // Longest keys first, so "Buyume Pet" is replaced before "Buyume".
  const pairs = [...Object.entries(items), ...Object.entries(chrome)]
    .filter(([k, v]) => !k.startsWith('_') && typeof v === 'string')
    .sort((a, b) => b[0].length - a[0].length);

  return { pairs, patterns };
}

const squash = s => s.replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();

const escapeRe = s => s.replace(/[.*+?^${}()|[\]\\]/g, m => '\\' + m);

// Anything still matching this after translation is a gap in the dictionary.
const TURKISH = /[ğşıİĞŞ]|\b(bir|ve|için|bu|ile|olarak|daha|gibi|çok|ama|lütfen|kadar|olan|sonra|önce|hale|gelir|eşya|için)\b/i;

export function createTranslator(dict) {
  // `pending` accumulates the ORIGINAL text of every chunk that came out still
  // Turkish, so browsing the mall produces the exact list of what is missing
  // instead of us guessing which pages matter.
  const stats = { changed: 0, reverted: 0, pending: new Map(), untouched: new Map() };

  // The mall indents and line-wraps inside descriptions, so the raw text rarely
  // matches a key character for character. Index by whitespace-squashed form too
  // and swap the whole chunk when that matches, keeping the outer padding.
  //
  // Short keys are matched on LETTER BOUNDARIES rather than as substrings: a
  // header like "Ay" (Month) or "Ara" (Search) occurs inside ordinary words --
  // Ayarlar, Kayit, Aralik -- and plain substring replacement mangles them. A
  // boundary still allows the cases that need it, such as "Eylul 2026".
  // \p{L} is used instead of \b because \b is ASCII-only and gets both ends
  // wrong on Turkish letters: it fails to match after the "s" of "Gecmis".
  const SHORT = 8;
  const bySquashed = new Map();
  const longPairs = [];
  const shortPairs = [];
  for (const [tr, en] of dict.pairs) {
    const k = squash(tr);
    if (!bySquashed.has(k)) bySquashed.set(k, en);
    if (k.length >= SHORT) longPairs.push([tr, en]);
    else shortPairs.push([new RegExp(`(?<!\\p{L})${escapeRe(tr)}(?!\\p{L})`, 'gu'), en]);
  }

  const chunk = text => {
    if (!text.trim()) return text;
    let out = text;

    const whole = bySquashed.get(squash(text));
    if (whole) {
      const lead = text.match(/^\s*/)[0];
      const tail = text.match(/\s*$/)[0];
      out = lead + whole + tail;
    } else {
      for (const [tr, en] of longPairs) if (out.includes(tr)) out = out.split(tr).join(en);
      for (const [re, en] of shortPairs) out = out.replace(re, en);
      for (const [re, rep] of dict.patterns) out = out.replace(re, rep);
    }

    if (!sameValues(out, text)) { stats.reverted++; out = text; }

    const left = squash(out);
    const key = squash(text);
    // The old gate here was `length >= 8`, which structurally hid every table
    // header -- Adet, Fiyat, Yil, Ay, Tarih, Esya, Sunucu were all too short to
    // ever be reported. Length is not evidence of anything; drop the floor.
    if (left.length >= 2 && TURKISH.test(left)) {
      stats.pending.set(key, (stats.pending.get(key) || 0) + 1);
    }

    if (out === text) {
      // Language detection has produced a false negative every single round, so
      // also record the plain fact: this chunk went through untouched. English
      // shows up here too and is easy to skip; Turkish can no longer hide.
      if (key.length >= 2) stats.untouched.set(key, (stats.untouched.get(key) || 0) + 1);
      return text;
    }
    stats.changed++;
    return out;
  };

  // The ONE attribute exception. A submit button's label lives in value=, so the
  // text walk cannot reach it -- that is why "Satin Al" stayed Turkish on the
  // purchase screen. Only type=submit/button/reset qualifies: value= on a text
  // or hidden input is data, not a label, and must never be rewritten. The
  // result is dropped if it would introduce a quote or angle bracket, so a
  // translation can never break out of the attribute.
  const BUTTON = /^<input\b[^>]*\btype\s*=\s*["']?(?:submit|button|reset)["']?[^>]*>$/i;
  const VALUE = /(\bvalue\s*=\s*)("[^"]*"|'[^']*')/i;

  const tag = part => {
    if (!BUTTON.test(part)) return part;
    return part.replace(VALUE, (whole, lead, quoted) => {
      const q = quoted[0];
      const inner = quoted.slice(1, -1);
      const out = chunk(inner);
      if (out === inner || out.includes(q) || /[<>]/.test(out)) return whole;
      return lead + q + out + q;
    });
  };

  const rewrite = html => {
    const parked = [];
    let work = html.replace(/<(script|style)\b[\s\S]*?<\/\1>/gi, m => {
      parked.push(m);
      return MARK_OPEN + (parked.length - 1) + MARK_CLOSE;
    });
    work = work.split(/(<[^>]+>)/).map(p => (p.startsWith('<') ? tag(p) : chunk(p))).join('');
    const restore = new RegExp(MARK_OPEN + '(\\d+)' + MARK_CLOSE, 'g');
    return work.replace(restore, (_, i) => parked[Number(i)]);
  };

  return { rewrite, stats };
}
